### ISSUE TITLE
Locale release procedures

### ISSUE THREAD

**Issue by chansen** [ThePilgrim/perlcldr#11]
Why is each locale released as a separate distribution when it has no dependencies besides `Locale::CLDR` and it's dependencies?
## 

chansen

**Comment by ThePilgrim** [comment]
I split it up so you could just install the languages you wanted rather than having to download the whole lot. There will be CPAN bundles for various regions relesed in the next couple of days. These should have gone up with the language data, but due to a combination of my upload  script accidentally hammering the CPAN uploader and commitments over the weekend this got delayed.

**Comment by chansen** [comment]
Five or ten megabytes of locale data is nothing, my iPhone has more than ten megabytes of locale data! 

What you have created is a nightmare for end users and vendor package managers, there is no way `Locale::CLDR` will be included in a vendor distribution. If I would like to develop a localized application, am I supposed to list all Locale::CLDR subclasses as a dependency?

The data could have been more compressed if you didn't ship each locale as a Perl module, and instead used a database like CDB or similar.

--
chansen

**Comment by kostya-ten** [comment]
+1

**Comment by ThePilgrim** [comment]
The way I devised it was to allow you to get all the data for the region you are interested in, so there is a bundle for North America and a separate one for the EU and so on. If you want everything then you get the everything bundle.
