### ISSUE TITLE
The split_grapheme_clusters & split_words doesn't work?

### ISSUE THREAD

**Issue by Perlover** [ThePilgrim/perlcldr#15]
Hi,

Your method doesn't work (perl v5.26.0 for example)?
Example

    use utf8;
    use strict;
    use Data::Dumper;
    use Locale::CLDR;
    
    my $locale = Locale::CLDR->new('cs_CZ');
    print Dumper($locale->split_grapheme_clusters(q{Chlopec})), "\n";

    
$VAR1 = 'C';
$VAR2 = 'h';
$VAR3 = 'l';
$VAR4 = 'o';
$VAR5 = 'p';
$VAR6 = 'e';
$VAR7 = 'c';

But 'Ch' - one letter and grapheme in Czech language

Other example, here is already the split_words:

    use utf8;
    use strict;
    use Data::Dumper;
    use Locale::CLDR;
    
    my $locale = Locale::CLDR->new('fr_FR');
    print Dumper($locale->split_words(q{celui qui l’écoute})), "\n";

$VAR1 = 'celui ';
$VAR2 = 'qui ';
$VAR3 = "l\x{2019}";
$VAR4 = "\x{e9}coute";

But i see there three words. I don't understand these functions... I see there simple splitting words  without rules of languages

    use utf8;
    use strict;
    use Data::Dumper;
    use Locale::CLDR;
    
    my $locale = Locale::CLDR->new('en_US');
    print Dumper($locale->split_words(qq{In messaging message it's written})), "\n";

$VAR1 = 'In ';
$VAR2 = 'messaging ';
$VAR3 = 'message ';
$VAR4 = 'it';
$VAR5 = '\'';
$VAR6 = 's ';
$VAR7 = 'written';

**Comment by Perlover** [comment]
Or, if your module works properly - i don't understand why there need these functions if they work standard work. I can split in chars through unicode decopmposition/composition (NFC() in Unicode::Normalize module). I expected for cs_CZ locale 'Chlopec' to 'Ch', 'l', ... and for fr_FR to 'celui', 'qui',  'l’écoute'' words

**Comment by Perlover** [comment]
I installed the Locale::CLDR::Locales::Cs & Locale::CLDR::Locales::Fr modules and tested my examples above
Same results :(

**Comment by ThePilgrim** [comment]
Thanks for the bug report, 
The CLDR data for version 31.0.1 doesn't provide specific segmentation data for the cs_CZ locale so my code falls back to the default root locale which treats Ch as separate letters, Saying that though the split words looks like its failing, it's supposed to to split the input into 'words' so that if you where displaying the input into an area with a fixed with each element in the array has to be treated as an atomic element and moved in full to the next line if it spans the end of a line.  This is supposed to stop you ending up with things like:

```
This is a s
hort line w
ith strang
e brakes
```

and allow you to split the input to give

```
This is a 
short line
with
strange
brakes
```

My French isn't good enough to know weather you can split celui qui l’écoute to look like

```
celui qui l’
écoute
```

or if it should be split as

```
celui qui 
l’écoute
```

I have some French speaking friends I can ask next week. Then I can check whether it's my code or the CLDR data that's at fault.

John

**Comment by Perlover** [comment]
Hi,

I research now some unicode documentations (Collation/sortkeys)...
I decide to close ticket because i think the solution to  my problem lies somewhere in a different plane.
Best regards ;-)
