### ISSUE TITLE
Bundle World doesn't install yi, eo, io, ia, jbo, prg, vo

### ISSUE THREAD

**Issue by wollmers** [ThePilgrim/perlcldr#25]
Version 0.34
Perl Version 5.20.1

These language codes are associated with region `'001' => 'World'`, but not installed by `Bundle::Locale::CLDR::World`:

```
yi
eo
io
ia
jbo
prg
vo
```

The codes `en` and `ar` associated with `World` are installed, but `en` is as special case. For `ar` I assume it defined as fall back for other locales, or associated directly to smaller regions like countries.

Direct installation of e. g.

`$ cpanm Locale::CLDR::Locales::Yi`

works. It is in the lib-path and 

`use Locale::CLDR::Locales::Yi;`

doesn't fail.

Something is wrong in `mkcldr.pl`.

**Comment by ehuelsmann** [comment]
Looking at the locale data here: https://www.unicode.org/cldr/cldr-aux/charts/34/summary/yi.html

and comparing that with the locale data here: https://www.unicode.org/cldr/cldr-aux/charts/34/summary/en.html

it seems to me that English is associated with various regions around the world whereas Yiddish isn't. And since World is the collection of all regions, it'd seem correct to me that this locale doesn't get installed. However, I would have expected this to be part of the "Everything" bundle. Which it isn't. That *does* seem to be a bug to me.

@ThePilgrim the bug here is that Yi isn't installed explicitly through ::Everything (it not being part of any of the bundles specified by Everything).

**Comment by ThePilgrim** [comment]
It should be part of World or something used by world, I've had problems with Yiddish before. I'll take a look at the CLDR containment data.

**Comment by ThePilgrim** [comment]
New test version 0.34.3 Uploaded to CPAN. This should fix the Problem with Yiddish and a few other languages
